name: Gitflow Enforcer

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  gitflow_enforcer:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to main from develop"
          exit 1
